// Categorys
export const SET_CURRENT_FAMILY = "SET_CURRENT_FAMILY";
export const SET_CURRENT_TILE = "SET_CURRENT_TILE";
export const SET_LATEST = "SET_LATEST";
export const SET_CURRENT_TILE_FROM_RECENT = "SET_CURRENT_TILE_FROM_RECENT";
export const SET_PREVIEW = "SET_PREVIEW";
export const ADD_TO_RECENT = "ADD_TO_RECENT";
export const DELETE_RECENT = "DELETE_RECENT";
export const SHOW_MODAL = "SHOW_MODAL";
